import { webglMetrics } from "../fields/metrics/webgl.js";
import { systemMetrics } from "../fields/metrics/system.js";
import { screenMetrics } from "../fields/metrics/screen.js";
import { renderingMetrics } from "../fields/metrics/rendering.js";
import { connectionMetrics } from "../fields/metrics/connection.js";
import {tcpMetrics } from "../fields/metrics/tcp.js";
import { hashString } from "../utils/hash.js";
import {trrd} from "../fields/trrd.js";
import { randomOffset } from "../utils/random.js";

export const buildMetricsContext = (ipInfo, userAgent) => {
    //==============TEMPORARY FIXES=================

    const lg = ipInfo.lang || "en"; // "ru"
    const plu = "PDF Viewer,Chrome PDF Viewer,Chromium PDF Viewer,Microsoft Edge PDF Viewer,WebKit built-in PDF";
    const mmt = "application/pdf,text/pdf";
    const bchk = "3223aeb6721e0d0917e7928181193ac88dcd62fbd5cadfbe7a2b2b473ecf58ee70f018dbdb1a1832e8dc6528387b0745971dbcd82384261e9a4e3f";
    //==============================================

    const g = [
        undefined,
        undefined,
        userAgent, // "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/
        String(systemMetrics.dvm), // "16",
        `[${lg}]`, // "[\"ru\"]",
        "0",
        systemMetrics.pf, // "Win32",
        String(screenMetrics.ars_h), // "1400",
        String(screenMetrics.ars_w), // "2560",
        undefined,
        plu, // "PDF Viewer,Chrome PDF Viewer,Chromium PDF Viewer,Microsoft Edge PDF Viewer,WebKit built-in PDF",
        mmt, // "application/pdf,text/pdf",
        bchk, // "3223aeb6721e0d0917e7928181193ac88dcd62fbd5cadfbe7a2b2b473ecf58ee70f018dbdb1a1832e8dc6528387b0745971dbcd82384261e9a4e3f",
        String(systemMetrics.hc) // "8"
    ].join("");

    return {
        "\"log2\"": "\"gl,tzp\"",
        "\"r3n\"": "33",
        "\"glvd\"": webglMetrics.glvd, //"\"Google Inc. (AMD)\"",
        "\"glrd\"": webglMetrics.glrd, //"\"ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001636) Direct3D11 vs_5_0 ps_5_0, D3D11)\"",
        "\"nddc\"": "0",
        "\"exp8\"": "0",
        "\"dp0\"": "false",
        "\"vco\"": "\"\"",
        "\"vcots\"": "false",
        "\"vch\"": "\"probably\"",
        "\"vchts\"": "true",
        "\"vcw\"": "\"probably\"",
        "\"vcwts\"": "true",
        "\"vc3\"": "\"maybe\"",
        "\"vc3ts\"": "false",
        "\"vcmp\"": "\"\"",
        "\"vcmpts\"": "false",
        "\"vc1\"": "\"probably\"",
        "\"vc1ts\"": "true",
        "\"vcmk\"": "\"maybe\"",
        "\"vcmkuts\"": "false",
        "\"vcq\"": "\"\"",
        "\"vcqts\"": "false",
        "\"nt_tcp\"": String(tcpMetrics.nt_tcp), //"23.80000001192093",
        "\"nt_dns\"": String(tcpMetrics.nt_dns), //"43.19999998807907",
        "\"nt_rd\"": "0",
        "\"nt_irt\"": String(tcpMetrics.nt_irt), // "-53.30000001192093",
        "\"nt_rt\"": String(tcpMetrics.nt_rt), //"91.30000001192093",
        "\"nt_tls\"": String(tcpMetrics.nt_tls), //"0.800000011920929",
        "\"nt_ttf\"": String(tcpMetrics.nt_ttf), //"145.60000002384186",
        "\"nt_swt\"": String(tcpMetrics.nt_swt), //"0.6000000238418579",
        "\"nt_csd\"": String(tcpMetrics.nt_csd), //"57941",
        "\"nt_nhp\"": String(tcpMetrics.nt_nhp), // "\"h3\"",
        "\"nt_rdc\"": String(tcpMetrics.nt_rdc), // "0",
        "\"nt_it\"": String(tcpMetrics.nt_it), //"\"navigation\"",
        "\"nt_prs\"": String(tcpMetrics.nt_prs), //"-22.600000023841858",
        "\"nt_esc\"": String(tcpMetrics.nt_esc), //"0.3999999761581421",
        "\"nt_ttrd\"": String(tcpMetrics.nt_ttrd), // "-0.9829059839509909",
        "\"nt_le\"": "0", //String(metrics.nt_le),
        "\"nt_dcle\"": "1", //String(metrics.nt_dcle)
        "\"nt_di\"": String(tcpMetrics.nt_di), //"162308",
        "\"nt_dc\"": "0", //String(metrics.nt_dc)
        "\"wdifrm\"": "false",
        "\"npmtm\"": "false",
        "\"wdif\"": "false",
        "\"ucdv\"": "false",
        "\"cssS\"": renderingMetrics.cssS, // "\"0.31,4.74,10.13,2.55,0.80,3.27,2.41,3.26,0.63\"",
        "\"css0\"": renderingMetrics.css0, // "\"47, 12, 0\"",
        "\"css1\"": renderingMetrics.css1, // "\"2.54588, 0.131341, -0.0613307, 0.0254484, -0.0293391, -0.544634, -2.38423, 0.989309, -0.0840349, 0.584538, -2.23654, 0.928023, -0.202524, 1.40874, -5.39005, 3.23654\"",
        "\"cssH\"": String(renderingMetrics.cssH), // "\"0px\"",
        "\"aco\"": "\"probably\"",
        "\"acots\"": "false",
        "\"acmp\"": "\"probably\"",
        "\"acmpts\"": "true",
        "\"acmpu\"": "\"maybe\"",
        "\"acmputs\"": "false",
        "\"acw\"": "\"probably\"",
        "\"acwts\"": "false",
        "\"acma\"": "\"maybe\"",
        "\"acmats\"": "false",
        "\"acaa\"": "\"probably\"",
        "\"acaats\"": "true",
        "\"ac3\"": "\"\"",
        "\"ac3ts\"": "false",
        "\"acf\"": "\"probably\"",
        "\"acfts\"": "false",
        "\"acmp4\"": "\"maybe\"",
        "\"acmp4ts\"": "false",
        "\"acmp3\"": "\"probably\"",
        "\"acmp3ts\"": "false",
        "\"acwm\"": "\"maybe\"",
        "\"acwmts\"": "false",
        "\"ocpt\"": "false",
        "\"ckwa\"": "true",
        "\"pf\"": systemMetrics.pf, // "\"Win32\"",
        "\"hc\"": String(systemMetrics.hc), // "8",
        "\"br_oh\"": String(screenMetrics.ars_h), //  "1400",
        "\"br_ow\"": String(screenMetrics.ars_w), //  "2560",
        "\"ua\"": `\"${userAgent}\"`,
        "\"wbd\"": "false",
        "\"ts_mtp\"": "0",
        "\"mob\"": "false",
        "\"lgs\"": `\"[\\\"${lg}\\\"]\"`,
        "\"dvm\"": String(systemMetrics.dvm), // "16",
        "\"tz\"": `${ipInfo.tz}`,
        "\"hdn\"": "false",
        "\"cdhf\"": "false",
        "\"eva\"": "40",
        "\"cokys\"": "\",loadTimes,csi,app\"",
        "\"niet\"": connectionMetrics.niet, // "\"4g\"",
        "\"nid\"": String(connectionMetrics.nid), // "10",
        "\"nisd\"": "false",
        "\"plu\"": `\"${plu}\"`,
        "\"plgod\"": "false",
        "\"plg\"": "5",
        "\"plgne\"": "true",
        "\"plgre\"": "true",
        "\"plgof\"": "false",
        "\"plggt\"": "false",
        "\"dffls\"": "\"Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Nunito Sans,Material Symbols Outlined,RMNeue-Regular,RMNeue-Bold,RMNeue-SemiBold\"",
        "\"bchk\"": `\"${bchk}\"`,
        "\"mmt\"": `\"${mmt}\"`,
        "\"trrd\"": String(trrd), //"1.2563821834946474",
        "\"wdifpnh\"": String(Math.floor((Date.now() + randomOffset(5000)) / 1000)), // "\"1716505461\"",
        "\"csssp\"": "\"\"",
        "\"hcovdr\"": "false",
        "\"plovdr\"": "false",
        "\"ftsovdr\"": "false",
        "\"orf\"": "\"\"",
        "\"br_w\"": String(screenMetrics.br_w), // "850",
        "\"br_h\"": String(screenMetrics.br_h), // "1279",
        "\"br_iw\"": String(screenMetrics.br_iw), // "850",
        "\"br_ih\"": String(screenMetrics.br_ih), // "1279",
        "\"ars_w\"": String(screenMetrics.ars_w), // "2560",
        "\"ars_h\"": String(screenMetrics.ars_h), //  "1400",
        "\"rs_w\"": String(screenMetrics.rs_w), // "2560",
        "\"rs_h\"": String(screenMetrics.rs_h), // "1440",
        "\"rs_cd\"": String(screenMetrics.rs_cd), // "32",
        "\"pr\"": "1",
        "\"so\"": "\"landscape-primary\"",
        "\"lg\"": `\"${lg}\"`,
        "\"isb\"": "false",
        "\"idp\"": "true",
        "\"crt\"": "0",
        "\"vnd\"": webglMetrics.vnd, //"\"Google Inc.\"",
        "\"bid\"": "\"NA\"",
        "\"med\"": "\"defined\"",
        "\"pltod\"": "false",
        "\"ccsT\"": "\"Error\\nat bn (https://jstag.oneboxtds.com/tags.js:275:15)\\nat Tn.P (https://jstag.oneboxtds.com/tags.js:2036:15)\\nat https://jstag.oneboxtds.com/tags.js:\"",
        "\"ccsB\"": "\"15)\\nat Tn.P (https://jstag.oneboxtds.com/tags.js:2036:15)\\nat https://jstag.oneboxtds.com/tags.js:169:20\\nat https://jstag.oneboxtds.com/tags.js:2322:17\"",
        "\"ccsH\"": "948571546",
        "\"mq\"": "\"aptr:fine, ahvr:hover\"",
        "\"nhi\"": "\"x86,64,false,,Windows,14.0.0,145.0.7632.160,false\"",
        "\"k_lyts\"": "48",
        "\"k_lytk\"": "\"kg20va`l\\\\'w8mh.71pdfoqcn[zy365x/\\\\,-4bt9siu=j;r]e\"",
        "\"emd\"": "\"denied\"",
        "\"bci\"": "true",
        "\"bcl\"": "1",
        "\"bct\"": "0",
        "\"bdt\"": "null",
        "\"stqe\"": "1384056798",
        "\"stqu\"": "0",
        "\"isf\"": "false",
        "\"isf2\"": "false",
        "\"fph\"": String(hashString(g)), // "\"1773671315\"",
        "\"sgb\"": "\"340374016\"",
        "\"sgd\"": "\"2022760486\"",
        "\"sgc\"": "\"3401505745\"",
        "\"jset\"": String(Math.floor(Date.now() / 1e3)), //"1773671315",
        "\"bpc\"": "1"
    };
}