export const audioMetrics = {
aco: "\"probably\"",
acots: "false",
acmp: "\"probably\"",
acmpts: "true",
acmpu: "\"maybe\"",
acmputs: "false",
acw: "\"probably\"",
acwts: "false",
acma: "\"maybe\"",
acmats: "false",
acaa: "\"probably\"",
acaats: "true",
ac3: "\"\"",
ac3ts: "false",
acf: "\"probably\"",
acfts: "false",
acmp4: "\"maybe\"",
acmp4ts: "false",
acmp3: "\"probably\"",
acmp3ts: "false",
acwm: "\"maybe\"",
acwmts: "false"
}